name: hive_game_client
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  chopper: ^4.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  hexagon: ^0.2.0-nullsafety.1
  internet_connection_checker: ^0.0.1+3
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^6.1.1
  build_runner: ^2.1.5
  chopper_generator: ^4.0.3
  

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
